language: python
python:
    - "2.7"
    - "3.4"
    - "nightly"
    - "pypy"

install:
    - pip install pytest pytest-cov
    - pip install -r requirements.txt
    - travis_retry python setup.py install
    
script:
    - python main.py

notifications:
  slack: rbirm:fjJKXGPbjyXSGAKKaOU6GWEh
